# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# load_cache: True
# load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

# best setting for fiber firework-gunshot dataset, CLAP-S
search_scale: [10, 10] 
search_step: [100, 10]



init_beta: 0.1
init_alpha: 0.1
train_epoch: 15
